### ISSUE TITLE
[SUGGESTION] The Ultimate ffmpeg -> webm encoding template

### ISSUE THREAD

**Issue by forart** [jeanslack/Videomass-presets#3]
Hi there,
dunno if aready present/implemented, but we just found this @VP8M8's [WebM-Guide](https://github.com/VP8M8/WebM-Guide) that seems interesting:
![](https://raw.githubusercontent.com/VP8M8/WebM-Guide/master/ffmpeg_WebM_Guide_v1.0.1.png)

Hope that inspires.

**Comment by jeanslack** [comment]
Thank you, The VP8 and VP9 codecs are already implemented on Videomass and the webm format as well.

**Comment by forart** [comment]
Of course anyway, according to @VP8M8, this should be an "optimized" template (but 6 years old)...

**Comment by jeanslack** [comment]
Hi,
I just updated the status of the presets supplied with Videomass and added the preset  [Video Encoding VP9-WebM.prst](https://github.com/jeanslack/Videomass-presets/blob/master/Presets_supplied_with_Videomass/Video%20Encoding%20VP9-WebM.prst)  following some webm encoding suggestion template.

Also these presets will be included and distributed with Videomass. Note that it is possible to create many combinations of presets using the A/V Conversion function and save them to the Presets Manager (including vp9/vp8 webm)

Anyway, thanks a lot again.
